FROM jenkins/jenkins:lts

# Install Docker
USER root
RUN apt-get update && \
    apt-get install -y \
    docker.io \
    docker-compose \
    && rm -rf /var/lib/apt/lists/*
# Install Terraform
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - && \
    echo "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && \
    apt-get install -y terraform
# Install Ansible
RUN apt-get update && \
    apt-get install -y \
    ansible \
    && rm -rf /var/lib/apt/lists/*
# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs \
    apt-get install npm -y \
    npm install -g corepack \
    corepack prepare yarn@4.2.2 --activate

# Install Maven
RUN apt-get update && \
    apt-get install -y maven

# Add Jenkins user to the docker group
RUN usermod -aG docker jenkins

USER jenkins