#cloud-config
# This cloud-config file is used to initialize a new droplet with the necessary configurations.

package_update: true
packages:
  - docker.io
  - docker-compose

users:
  - name: ${username}
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_pub_key}
    home: /home/${username}
    create_home: true

write_files:
  - path: /etc/sudoers.d/${username}
    content: |
      ${username} ALL=(ALL) NOPASSWD: ALL
    owner: root:root
    permissions: '0440'

runcmd:
  - apt update
  - sudo usermod -aG docker ${username}
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo systemctl enable docker
  - sudo systemctl start docker

